name: flutter_application_1

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.3
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.9.0
  sqflite_common_ffi: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/iphone12pro.jpg
    - assets/iphone13.jpg
    - assets/iphone15.jpg
    - assets/iphone17.jpg
    - assets/iphonexr.jpg
    - assets/iphone16.jpg